"""Configuration module for SGR discount manager."""

from .constants import (
    DATA_DIR,
    DEFAULT_API_BASE_URL,
    DEFAULT_API_KEY,
    DEFAULT_CART_VALUE,
    DEFAULT_CHURN_PROBABILITY,
    DEFAULT_MODEL,
    DEFAULT_PROFIT_MARGIN,
    DEFAULT_TEMPERATURE,
    HIGH_CHURN_THRESHOLD,
    LOW_CHURN_THRESHOLD,
    OFFLINE_STORE_PATH,
    ONLINE_STORE_PATH,
    SQL_DIR,
)

__all__ = [
    "DATA_DIR",
    "DEFAULT_API_BASE_URL",
    "DEFAULT_API_KEY",
    "DEFAULT_CART_VALUE",
    "DEFAULT_CHURN_PROBABILITY",
    "DEFAULT_MODEL",
    "DEFAULT_PROFIT_MARGIN",
    "DEFAULT_TEMPERATURE",
    "HIGH_CHURN_THRESHOLD",
    "LOW_CHURN_THRESHOLD",
    "OFFLINE_STORE_PATH",
    "ONLINE_STORE_PATH",
    "SQL_DIR",
]
